version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - docker-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            export VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
            docker build --build-arg KUBE_LATEST_VERSION=$VERSION --build-arg VCS_REF=`git rev-parse — short HEAD` --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` --cache-from=app -t app .
            docker tag app gofunky/kubernetes:$VERSION
            docker tag app gofunky/kubernetes:latest
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USR -p $DOCKER_PWD
              docker push gofunky/kubernetes:$VERSION
              docker push gofunky/kubernetes:latest
            fi
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: docker-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: docker-hub
