#!/bin/bash

export VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)

# $IMAGE_NAME var is injected into the build so the tag is correct.
docker build --build-arg KUBE_LATEST_VERSION=$VERSION \
  --build-arg VCS_REF=`git rev-parse — short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  -t $IMAGE_NAME .

docker tag $IMAGE_NAME $VERSION
